name: planqtn Library Checks
run-name: ${{ github.actor }} is checking the planqtn library 🚀
on:
  pull_request:
    paths:
      - "qlego/**"
      - "pyproject.toml"

  push:
    paths:
      - "qlego/**"
      - "pyproject.toml"

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: step-security/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          paths_ignore: '["**/*.md"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  qLEGO-Lib-Checks:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade uv
          uv pip install -r pyproject.toml --all-extras --system
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          check/qlego
