name: Push UI Image
run-name: ${{ github.actor }} is pushing the UI image
on:
  workflow_run:
    workflows: ["UI Checks"]
    branches: [main, hotfix/*]
    types:
      - completed
jobs:
  Push-UI-Image:
    environment:
      name: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish new UI image
        env:
          DOCKER_REPO: ${{ vars.DOCKER_REPO }}
        run: |
          hack/htn images ui --build --push -q
